### ISSUE TITLE
Hazelcast management center can't redeploy

### ISSUE THREAD

**Issue by jayar** [hazelcast/charts#105]
After a successfully first deploy, then after redploying the management center, it will fail with the following log message:
executing command specified by MC_INIT_CMD
ERROR: Could not add new Cluster Config. Reason: Cluster config dev already exists!
To see the full stack trace, re-run with the -v/--verbose option. 

Expected behavior is that restart will work fine. 
If persistence is disabled, it is working fine. But then I have to create master password every time management center is restarted.  

Helm version:
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}

Hazelcast chart version: hazelcast-3.0.5
App version: 4.0

Kubectl version:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

values.yaml:
mancenter:
  persistence:
    storageClass: nfs-client
  service:
    type: NodePort

**Comment by mesutcelik** [comment]
Hi @jayar ,
Can you share your install and redeploy commands?

**Comment by emre-aydin** [comment]
@mesutcelik it looks like the command is run for the second time when the container is restarted and it fails to create the same user as it already exists. Normally, we want this command to fail when such condition occurs but in this case we need to print an error and continue. We have several options for solving the issue:

1. Command returns 0 but prints the error message - I wouldn't prefer this as it breaks user expectations by returning 0 even though the command failed
2. Adding a flag to not fail if the cluster already exists (which would be mentioned in the error log when the cluster already exists) - This would work but since it's not the default command, Docker users will need to adapt in their second run of the command. Not a huge problem IMO.
3. Implementing a command to list the configured cluster names - It would require more work on the user but the extra command might be useful in other places as well.

Which one do you think is a better way considering the usual way of doing things in containers? Do you have a better solution in mind?

**Comment by mesutcelik** [comment]
I think you are talking about he re-run of [that script](https://github.com/hazelcast/charts/blob/dec16bdecf67a282b8de4c6ef15586dc08c99b1d/stable/hazelcast/templates/mancenter-statefulset.yaml#L104) right?

Can't you update script to add cluster if it does not exist and do nothing or override if it exists?
I am not sure that fits any of your 3 options above?

**Comment by leszko** [comment]
Yeah, I agree with @mesutcelik , I think the script command should have an option like `--force` or `--overwrite` to create the user if it does not exist. To me it sounds like a common scenario (not only for Docker related stuff) that you re-use the MC persistent data, but just want to re-run MC service.

@emre-aydin , what do you think?

**Comment by emre-aydin** [comment]
@mesutcelik @leszko so you're basically suggesting option 2. We can do this for both user creation and cluster addition. Let me create an issue for 4.0.2 (which is the next patch release of MC).

**Comment by leszko** [comment]
Thanks @emre-aydin !

**Comment by jayar** [comment]
That sounds great, let me know I need to test anything.

**Comment by boatmisser** [comment]
@emre-aydin Have you created an issue? Could you reference it here so we can track its progress.
Thanks!

**Comment by emre-aydin** [comment]
@boatmisser here it is but it's in a private repo. The PR for fixing it is merged and will be released in MC v4.0.2.

**Comment by boatmisser** [comment]
@emre-aydin  thanks for the update; really appreciate the fast response; do we have a rough ETA for MC v4.0.2.

**Comment by emre-aydin** [comment]
@boatmisser We're trying to limit patch releases to once a month. 4.0.1 was released on 9th of March. I guess it will be released around mid April.

**Comment by mattrapa** [comment]
Any updates on this one, please. Still getting:
---
executing command specified by MC_INIT_CMD for container initialization
ERROR: Cluster null already exists.

To see the full stack trace, re-run with the -v/--verbose option.
---
using image: hazelcast/management-center:4.0.2

Thank you

**Comment by mesutcelik** [comment]
I think the flag introduced by MC has not been used in helm chart yet. @emre-aydin ?

**Comment by emre-aydin** [comment]
I don't know about the helm chart but the flag was introduced in MC 4.0.2 which is released, so we can make use of it in the helm chart.

**Comment by mattrapa** [comment]
Where is this flag documented please?

**Comment by emre-aydin** [comment]
@mattrapa `mc-conf` commands are self documenting, which means when you execute a command with no options (or with `--help` appended), it shows available options. In this case, it's the `--lenient` boolean flag that you're looking for.

**Comment by mattrapa** [comment]
Thank you :)

**Comment by mesutcelik** [comment]
@mattrapa It would be appreciated if you can contribute. I think it is relatively simple change.

**Comment by mattrapa** [comment]
Yep let me figure out how to open a PR - I will also try and add additional labels for Prometheus service monitor.
