### ISSUE TITLE
Management Center Persistence in Helm Charts

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/charts#120]
`mancenter.persistence.enabled` parameter is used to create Persistence Volume for MC but we need to create PV everytime MC is deployed with helm chart. 

I believe we should remove `mancenter.persistence.enabled`. @emre-aydin What do you think?

**Comment by emre-aydin** [comment]
MC always needs access to local file system if one doesn't want to configure everything from scratch after a restart. I'm not sure what was the purpose of the parameter but seems it can be removed.

**Comment by leszko** [comment]
I think the parameter still makes sense. If you set it to `false`, then MC will start from scratch every time. That may actually be good if you would like to play with Helm Chart and MC, but you don't have access to any storage.

**Comment by emre-aydin** [comment]
> I think the parameter still makes sense. If you set it to `false`, then MC will start from scratch every time. That may actually be good if you would like to play with Helm Chart and MC, but you don't have access to any storage.

Makes sense. Let's close the issue then.
