### ISSUE TITLE
Please make deleteGracePeriodSeconds configureable

### ISSUE THREAD

**Issue by xrow** [hazelcast/charts#123]
Hi,

the issue is that the statefull sets do not terminate instantanly or fast. We want to configure it. The default is set in the cluster 600 which might be a long time.

**Comment by leszko** [comment]
@xrow Thanks for raising it. Actually it is configurable with the [gracefulShutdown.maxWaitSeconds](https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/values.yaml#L96) parameter. Check if it works for you.

**Comment by xrow** [comment]
Thanks that helps. Please close.
