### ISSUE TITLE
Can't install hazelcast release in various namespaces

### ISSUE THREAD

**Issue by kudodenko** [hazelcast/charts#133]
For some development improvement we are using various namespace for various environment.
In the case we can't install only one hazelcast release, every other deployment lead to next error:
```
helm upgrade --install --wait hazelcast hazelcast/hazelcast --set mancenter.persistence.enabled=true,mancenter.ingress.enabled=true,mancenter.ingress.hosts={hazelcast-uat.company.com},mancenter.ingress.annotations."kubernetes\.io/ingress\.class=nginx",cluster.memberCount=3,mancenter.service.type=ClusterIP --namespace=system-uat
Release "hazelcast" does not exist. Installing it now.

Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "hazelcast" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "system-uat": current value is "system-test"
```

I believe that the ability to install multiple releases in the same kubernetes cluster(but different ns) is a must for any charts.

**Comment by leszko** [comment]
@kudodenko I created a PR to solve it (#135). In the meantime, you can install multiple Hazelcast cluster by giving a separate name for each namespace.

Btw. thanks for reporting it! 👏

**Comment by kudodenko** [comment]
@leszko thanks!
