### ISSUE TITLE
Setting service.nodePort ist not supported

### ISSUE THREAD

**Issue by xrow** [hazelcast/charts#142]
In this file (https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/templates/service.yaml
) I would like to be able to set a static node port.

Plz add:

`  nodePort: {{ .Values.service.nodePort }}`

**Comment by hasancelik** [comment]
Hi @xrow,

Good idea 👍  It would be great, if you can create a PR for it. Is it ok for you?
