### ISSUE TITLE
Cannot start only management service 

### ISSUE THREAD

**Issue by letmagnau** [hazelcast/charts#161]
Hi I've a K8 cluster and embedded in my application I use hazelcast with Hibernate53

if I run in docker all goes ok only starting  a managment hazelcast as image

with this chart ., it will always start a statefulset app trying to find the pod the he want to create
but I want only the management cluster 

There is a way to start only the management ? I create a custom service  on 5701 managed by my app

best regards

Piero

**Comment by hasancelik** [comment]
Hi @letmagnau,

Management center only deployment is not possible for now. I think, we can add `enabled` parameter for Hazelcast IMDG like we did for MC:
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/values.yaml#L203
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/mancenter-statefulset.yaml#L1

It would be great, if you can create a PR for this enhancement. Is it ok for you?

**Comment by jisnardo** [comment]
Here is the pr https://github.com/hazelcast/charts/pull/168 @hasancelik

**Comment by hasancelik** [comment]
Great, thanks for the PR @jisnardo 👍

**Comment by hasancelik** [comment]
fixed by https://github.com/hazelcast/charts/pull/168
