### ISSUE TITLE
Upgrade default MC to stable version (4.2020.12)

### ISSUE THREAD

**Issue by huseyinbabal** [hazelcast/charts#174]
Beta version of MC is being used within the chart, we need to use stable one which is `4.2020.12`

**Comment by huseyinbabal** [comment]
@leszko @hasancelik could you please tell me, do I need to upgrade `HZ 4.1`, `MC 4.2020.12` for all the chart values?

**Comment by hasancelik** [comment]
@huseyinbabal the IMDG charts are already using 4.1 so you can just update MC tag/version at values.yamls?
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/values.yaml#L222
https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/values.yaml#L255

**Comment by huseyinbabal** [comment]
> @huseyinbabal the IMDG charts are already using 4.1 so you can just update MC tag/version at values.yamls?
> https://github.com/hazelcast/charts/blob/master/stable/hazelcast/values.yaml#L222
> https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/values.yaml#L255

Understood, what about jet charts?

**Comment by hasancelik** [comment]
@huseyinbabal As far as I can see, they are still using JET specific management center, updating it from 4.3 to directly 4.2020.12 might cause some issues so manual testing might be required. cc: @frant-hartm
