### ISSUE TITLE
More pods than default clusterMemberCount

### ISSUE THREAD

**Issue by wildnez** [hazelcast/charts#206]
The default count of cluster members is 2 (as per the documentation here: https://github.com/hazelcast/charts/tree/master/stable/hazelcast-enterprise) but the deployment creates 3 IMDG pods. Here is the install command:
helm install rahul-march15v2-helm-dep --set hazelcast.licenseKey="LICENSE_KEY" --set securityContext.runAsUser=1000560000,securityContext.runAsGroup=1000560000,securityContext.fsGroup=1000560000 hazelcast/hazelcast-enterprise

Either the default member count is documented wrong or configured wrong in the yaml.

**Comment by hasancelik** [comment]
fixed by https://github.com/hazelcast/charts/commit/23fcf151da5a4d7b10242cb3e03872e2c79c4c51
