### ISSUE TITLE
mancenter.persistence.storageClassName 

### ISSUE THREAD

**Issue by megaterrarc** [hazelcast/charts#230]
Include property mancenter.persistence.storageClassName

**Comment by hasancelik** [comment]
Hi @megaterrarc,

`storageClassName` is already configurable for Management Center, please check:
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/values.yaml#L329
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/mancenter-statefulset.yaml#L206

I am closing this issue, feel free to reopen if needed.

**Comment by megaterrarc** [comment]
Hi @hasancelik,

Really. Properties Update Readme.

  https://github.com/hazelcast/charts/tree/master/stable/hazelcast

![image](https://user-images.githubusercontent.com/9610355/124946008-08054500-dfe5-11eb-996e-022bb42d3cb9.png)

**Comment by hasancelik** [comment]
fixed by https://github.com/hazelcast/charts/commit/9a9a4a2343ec3df1f4509790da8070031be00f1d

Thanks for your report @megaterrarc 👍
