### ISSUE TITLE
Gett

### ISSUE THREAD

**Issue by robinroos** [hazelcast/charts#231]
I installed Hazelcast Management Center (only) using a version of this helm chart some time back.  I believe the installed versions were:

Hazelcast Management Center 4.2020.12, Jet client 4.3-with-IMDG-4.1, Hazelcast client 4.1

I deploy my cluster separately, and that is now using Hazelcast (Jet) 5.0-SNAPSHOT.

I am trying to re-install Management Center (technical issues on my side), and hope that by doing so I will get a version more recent than 4.2020.12, but I would like to know if it is possible to influence the tag for the install.  Specifically I would happily install the Management Centre of 5.0-SNAPSHOT.

Thanks, Robin.

**Comment by leszko** [comment]
You can install 5.0-SNAPSHOT. Hazelcast and MC 5.0 are mostly backwards-compatible with 4.x, so the Helm Chart should work correctly.

Closing, reopen if needed.

**Comment by robinroos** [comment]
How can I use this helm chart to install MC 5.0-SNAPSHOT ?

**Comment by leszko** [comment]
I think that yes.

**Comment by robinroos** [comment]
Do I have to pass something to --set ?

**Comment by robinroos** [comment]
e.g. --set-string image.tag="5.0-SNAPSHOT" ?
