### ISSUE TITLE
Adding custom JAR file to the Management Center classpath

### ISSUE THREAD

**Issue by IreneGhafari-TomTom** [hazelcast/charts#245]
Hi,

I am using Helm version ```3.7.4``` for setting up hazelcast and mancenter.

From the management center SQL browser and Map browser I got error: ```java.lang.ClassNotFoundException```

To solve this for the management-center, I created a custom Dockerfile that extends the 4.2021.04 version, and copied the jar file to the image and set the env variable ```MC_CLASSPATH``` like below:

```
FROM hazelcast/management-center:4.2021.04

ARG JAR_FILE

# Adding custom JAR to the classpath
ADD target/${JAR_FILE} /data/custom/some-jar.jar

ENV MC_CLASSPATH="/data/custom/some-jar.jar"
```

But I still get the error. 

I saw that I can mount a volume by using ```customVolume``` in helm. but having a custom dockerfile was easier for me. Is this not the right way? should I really mount a volume? or am I missing something else?

Thank you in advance

**Comment by mizbahcelik** [comment]
Hi @IreneGhafari-TomTom  ,
I tried your custom Dockerfile and got the same error on SQL Browser.
Addding my custom jars to hazelcast together with management-center solved the problem.
I used command taken from https://hub.docker.com/r/hazelcast/hazelcast under title “Extending CLASSPATH with new jars or files”. 
`docker run -p 5701:5701 -e CLASSPATH="/opt/hazelcast/CLASSPATH_EXT/*" -v <MY_DIR_PATH_OF_CUSTOM_JAR>:/opt/hazelcast/CLASSPATH_EXT hazelcast/hazelcast`

Also as you mentioned customVolume in helm is the recommended way.
I tried and it works if you follow the updated [README.md](https://github.com/hazelcast/charts/blob/master/stable/hazelcast/README.md#adding-custom-jar-files-to-the-imdgmanagement-center-classpath).

If it is ok for you, I am closing the issue? Feel free to reopen if needed.
