### ISSUE TITLE
Change 'hotRestart' parameters to 'persistence'

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/charts#280]
I suggest changing the `hotRestart` parameter names to `persistence` to be consistent with the [changes in Hazelcast 5](https://docs.hazelcast.com/hazelcast/5.0/release-notes#api-changes). The following are the parameters that should be changed (all that I'm aware of):

* hotRestart.enabled
* hotRestart.existingClaim
* hotRestart.accessModes
* hotRestart.size
* hotRestart.hostPath

**Comment by hasancelik** [comment]
fixed by #333
