### ISSUE TITLE
Ingress with Prefix path : css and js files not found

### ISSUE THREAD

**Issue by stockersky** [hazelcast/charts#304]
I am trying to install Hazelcast with this Helm Chart.

I have only one host for several apps so I use Prefix Path in the ingress url.

For now, I am just trying to make the "mancenter" work with "/hazelcast" prefix (as it's a UI, I could quickly check that the release would work. I might change the prefix later...)

I succeed at hitting the ingress  but css & js files are not found :

![image](https://user-images.githubusercontent.com/22478549/186159939-dc429434-bce4-4d74-abe3-ce4df4064b0f.png)

Indeed, the requested url's for those files are missing the "/hazelcast" prefix.

Here are some snippets :

Mancenter-ingress.yaml

```yaml
rules:
  {{- $serviceName := include "mancenter.fullname" . -}}
  {{- if .Values.mancenter.ingress.hosts }}
  {{- range $host := .Values.mancenter.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /hazelcast(/|$)(.*)
            pathType: Prefix
            backend:
                service:
                  name: {{ $serviceName }}
                  port:
                    number: 8080
```

Values.yaml

```yaml
ingress:
    enabled: true
    annotations: 
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
    - app.domain.com
    tls:
    - secretName: certificat-tls-dev
      hosts:
      - app.domain.com
```

And the final manifest : 

```yaml
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: hazel
    meta.helm.sh/release-namespace: sit-dev01
    nginx.ingress.kubernetes.io/rewrite-target: /hazelcast/$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
  creationTimestamp: "2022-08-01T15:15:41Z"
  generation: 10
  labels:
    app.kubernetes.io/instance: hazel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hazelcast-mancenter
    helm.sh/chart: hazelcast-5.4.6
  name: hazel-hazelcast-mancenter
  namespace: dev
  resourceVersion: "232573002"
  uid: a5b6d5d6-85e1-4443-9698-e6129c4417f2
spec:
  rules:
  - host: app.domain.com
    http:
      paths:
      - backend:
          service:
            name: hazel-hazelcast-mancenter
            port:
              number: 8080
        path: /hazelcast(/|$)(.*)
        pathType: Prefix
  tls:
  - hosts:
    - app.domain.com
    secretName: certificat-tls-dev
```

This works for some other Angular apps that I have deployed.

I have tried all kinds of combinations but the prefix is never happened to the static javascript & css files and I get a 404 Not Found.

**Comment by semihbkgr** [comment]
Hi @stockersky

As far as I understand, you want to set custom Ingress path for Management Center. To be able to do that, you also have to set context path of Management Center.

`hazelcast.mc.contextPath` : Prefix of all URL paths in Management Center. Default: ' ' (empty).

To set context path, you can declare `mancenter.contextPath` field in values.yaml.

In your case, context path should be set as:

```yaml
...
mancenter:
  ingress:
    enabled: true
  contextPath: /hazelcast
...
```
