### ISSUE TITLE
Question: What is the correct usage of `service.name`

### ISSUE THREAD

**Issue by MayurDhande-GSLab** [hazelcast/charts#323]
Hello,

I have a question regarding configuring this chart. Below is my `values.yaml` file,
```
service:
  name: cachehost
```
- Question: `service.name` is only used when `service.create` is `false`. But setting it to `false` does not create the service (removes the service if already created). So basically this configuration is of no use.

Please guide on this. Thank you

**Comment by MayurDhande-GSLab** [comment]
Created #324 for this.

**Comment by semihbkgr** [comment]
Hi @MayurDhande-GSLab
Thanks for the issue!

The `service.name` filed is used to declare existing service name.

Name of Service, by default generated using the fullname template. 
To override, two condition need to be met: service.create=false (service must exist before chart deploy) and value of `service.name` must not be nil.

**Comment by MayurDhande-GSLab** [comment]
Hi @semihbkgr 
Suppose I have an existing service deployed, and now I want to override its name, so I will set `service.create=false` and `service.name=newName`, then when I apply the chart, it removes the deployed service and does not create a new one as basically `service.create=false`.

If `service.name` is available, then that must be used, else use the default generated using fullname template.
I don't understand why `service.create` has anything to do with what service name we want to set.

I have created a PR for this change https://github.com/hazelcast/charts/pull/324

**Comment by semihbkgr** [comment]
I don't understand what you mean by saying `when I apply the chart, it removes the deployed service`. It seems like it is not 
 a possible case and I cannot reproduce it. Can you share your configurations.

**Comment by MayurDhande-GSLab** [comment]
@semihbkgr Sorry, I meant installing the chart,
I am installing the chart using,
```
helm install my-release --set service.name=cachehost hazelcast/hazelcast
```
Then, service name is not what I specified in `service.name`, it is auto generated.
The documentation says, `service.create` must be `false`, in order for `service.name` to be used., but if I install the chart,
```
helm install my-release --set service.create=false --set service.name=cachehost hazelcast/hazelcast
```
then above line does not even create a kubernetes `Service` object (because `service.create` is false)

My point is `service.name` configuration does not seem to be used in any scenario.
I hope you got my point.

Or, to answer my query, can you please provide `helm install` steps to install the chart that will create a k8 Service object named `cachehost` ?

**Comment by semihbkgr** [comment]
The correct usage of `service.create` and `service.name` is that:

To create a new service with chart install, you do not need to do anything special, it is the default behavior.

However, in case that you have an already existing service, and you want to use that service instead of creating new one. Then your config should be like this.

```yaml
service:
  create: false
  name: <existing service name>
```

**Comment by MayurDhande-GSLab** [comment]
Thanks for the information.
Having an existing k8 Service running, when I use your configuration, the `helm diff` plugin sees `service.create` is now `false` and as removes the k8 Service altogether, (since Service.yaml template would only be installed when `service.create` is true)

**Comment by semihbkgr** [comment]
That is already what we expect when `service.create` is set to false.

**Comment by MayurDhande-GSLab** [comment]
Correct me if I am wrong,
- Create service only if `service.create` is `true` with the default templatized name.
- Existing service is deleted (by `helm diff`) if `service.create` is `false`.
- finally, `service.name` is used only when `service.create` is `false`. But in this case if service is going to get deleted (because `create=false`, then `service.name` will never be used.

My point is value provided in `service.name` will be assigned to k8 service object (since it will never exist due to `service.create`)

**Comment by MayurDhande-GSLab** [comment]
There is difference in the documentation of hazelcast vs hazelcast enterprise. Below is the enterprise documentation,
![image](https://user-images.githubusercontent.com/25840389/202665463-eaf34192-0ca7-446b-9f9f-7162832b703c.png)

This correctly documents the usage, i.e. provide `service.name` if you want to override the name of the service that will going to be installed. (Although the template code of enterprise also does not work as per documented)

**Comment by MayurDhande-GSLab** [comment]
> service.name is not used to set the name of service which will be created by helm install. It is just used to declaring the existing service's name.

Why to even declare the name of existing service, if the name is anyways going to get auto generated. What is the point of having that name in the configuration file. That's just opposite of what configuration means.

**Comment by MayurDhande-GSLab** [comment]
Expected behavior should be as documented in the enterprise documentation, that is,
If `service.name` is provided, use that to while naming the k8 Service object, else use the templatized auto generate name.
(and, create service only if `service.create=true`)

**Comment by MayurDhande-GSLab** [comment]
@semihbkgr, I found the merged PR that did this change https://github.com/hazelcast/charts/pull/54
It still does not convince me, but closing I am this issue.
