### ISSUE TITLE
Charts repo has no tags in releases section

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/charts#35]
I see no tagging here but we do have releases.
https://github.com/hazelcast/charts/tags

It would be good to tag repo after each release so that we can simply check previous versions in case of troubleshooting.

**Comment by leszko** [comment]
@mesutcelik How would you tag it? The repo has 4 different helm charts and each has a different version.

**Comment by mesutcelik** [comment]
I do not know. Maybe using helm chart name in the tag..
