### ISSUE TITLE
Pod Security Review Feedback 

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/charts#38]
- Why do we have two ServiceAccount definition? [1](https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/statefulset.yaml#L86) [2](https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/statefulset.yaml#L100)
- Is [this](https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/statefulset.yaml#L93) if condition relevant as `runAsUser` is always set?
- `fsgroup` is not part of [SecurityContext](https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/statefulset.yaml#L90). see the [doc](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#securitycontext-v1-core) 
- Do you think we should add `RunAsGroup` field?

**Comment by mesutcelik** [comment]
I see some of them already mentioned in the PR
https://github.com/hazelcast/charts/pull/30

**Comment by leszko** [comment]
> * Why do we have two ServiceAccount definition? [1](https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/statefulset.yaml#L86) [2](https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/statefulset.yaml#L100)
This is fine I guess. One `serviceAccountName` is used for the resource `StatefulSet`. The other `serviceAccountName` is used for the resource `Pod`.

> * Is [this](https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/statefulset.yaml#L93) if condition relevant as `runAsUser` is always set?
It looks fine. If it's empty then it's not set. I think that in YAML empty field is the same as not set field.

> * `fsgroup` is not part of [SecurityContext](https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/statefulset.yaml#L90). see the [doc](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#securitycontext-v1-core)

Yes, you're right, it was removed in #37 .

> * Do you think we should add `RunAsGroup` field?
Yeah, I think we could add it. For clarity I've created a separate GH Issue #41

**Comment by mesutcelik** [comment]
> This is fine I guess. One serviceAccountName is used for the resource StatefulSet. The other serviceAccountName is used for the resource Pod.

I see that caused some lint errors. Apparently, @dacleyra has removed one of them in the PR
https://github.com/hazelcast/charts/pull/30/files#diff-f68bdae4b1dd62c1742d595338dba9c8L101

> It looks fine. If it's empty then it's not set. I think that in YAML empty field is the same as not set field.

What happens if we just remove if condition and move `runAsNonRoot: true` just under `runAsUser`?

**Comment by leszko** [comment]
> I see that caused some lint errors. Apparently, @dacleyra has removed one of them in the PR
> https://github.com/hazelcast/charts/pull/30/files#diff-f68bdae4b1dd62c1742d595338dba9c8L101

Actually you're right. That's the fix: #42

> What happens if we just remove if condition and move `runAsNonRoot: true` just under `runAsUser`?

If `runAsUser` is not defined, then you run as a root. So you don't want to have `runAsNonRoot` defined. That's my understanding. For example, you mount a volume which requires root permissions then you need to run your container as a root. Does it make sense?

**Comment by mesutcelik** [comment]
I am probably focusing on readability... I feel refactoring into following would be more compact. Is there any problem with the following statement? 

```
       securityContext:
          {{- if .Values.securityContext.runAsUser }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsNonRoot: true
          {{- end }} 
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false

```

**Comment by leszko** [comment]
@mesutcelik You're change is not just about readability. But I guess it's fine, we should never need to write to the root filesystem or allow priviledge escalation, even if you run as a root. I've created a PR to fix it. PTAL.

https://github.com/hazelcast/charts/pull/43
