### ISSUE TITLE
Add `runAsGroup`

### ISSUE THREAD

**Issue by leszko** [hazelcast/charts#41]
By default the Pod uses the group 0 (root). We could add the parameter `runAsGroup` (as reported by @mesutcelik in #38 ).

**Comment by cristina-sirbu** [comment]
Hello! May I take this issue please?

**Comment by Holmistr** [comment]
@cristina-sirbu And the issue is yours! :tada: I see you already sent a PR, wow! In that case, let me get the reviews for it.
