### ISSUE TITLE
Create Continuous Delivery process

### ISSUE THREAD

**Issue by leszko** [hazelcast/charts#44]
Currently, Hazelcast Helm Chart repo i published by the Helm-Chart-release pipeline in Jenkins. However, there are the following drawbacks comparing the to the [official Helm Chart repo](https://github.com/helm/charts):

* The Jenkins release is not triggered automatically (you need to go into Jenkins and click "Build" to release new chart versions)
* There are not tests run (so, actually you need to test the each chart manually before releasing)
* There is no check if the Chart version was bumped up (so, if you forget about it, the new chart will override the existing chart)
* There are no notifications to the PR sent (because there are not tests).

Some guidelines how to create a Continuous Delivery pipeline for the Helm Charts:
* https://github.com/helm/chart-testing
* https://github.com/helm/chart-testing/tree/master/examples/kind

**Comment by mesutcelik** [comment]
Have we implemented any of those? @leszko @hasancelik

**Comment by leszko** [comment]
No, what we have is the pr-builder.  Thanks @hasancelik! 
But we'll need is a pipeline for the automatic release.
