### ISSUE TITLE
MC Built-In User Creation while helm install

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/charts#61]
When we install hazelcast helm charts, we have to signup and then login all the time after the installation. Instead of doing that, helm chart can create a admin user and keep a generated password in a Secret. 

This is a sample Dockerfile which creates a builtin user.
https://github.com/hazelcast/hazelcast-docker-samples/blob/master/management-center-built-in-user/Dockerfile#L5

**Comment by mesutcelik** [comment]
waiting for https://github.com/hazelcast/management-center-docker/issues/26

**Comment by cristina-sirbu** [comment]
The management-center-docker#26 issue has been solved. And I would like to take a look into this one, but I don't understand exactly what do you mean by "generated password"? @mesutcelik If you can provide more detalis around this I would be happy to help with it

**Comment by mesutcelik** [comment]
I think we just need to remove this[ lifecycle hook](https://github.com/hazelcast/charts/pull/77/files#diff-0d291338c01e1a63f37d664664197229R86) from PR. 

When I said generated, I actually meant adding password into Secret beforehand so you can assign required environment variables [here](https://github.com/hazelcast/charts/pull/77/files#diff-0d291338c01e1a63f37d664664197229R100).

**Comment by cristina-sirbu** [comment]
I see. Took a look on your PR. Seems like your fork only needs an update and removing that lifecycle indeed. I will take a look around to help with another issue. 😄

**Comment by mesutcelik** [comment]
What do you think about implementing initContainers?
https://github.com/hazelcast/charts/issues/18
