### ISSUE TITLE
Management Center health URL

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/charts#62]
This chart https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/templates/mancenter-statefulset.yaml#L58 says use port 8080 or 8443 for the health URL

The health URL is on 8081, https://docs.hazelcast.org/docs/management-center/3.12.5/manual/html/index.html#enabling-health-check-endpoint as always by HTTP not HTTPS

**Comment by mesutcelik** [comment]
In addition to that, we need to enable health check by default on MC deployment.
`-Dhazelcast.mc.healthCheck.enable=true`
