### ISSUE TITLE
sync script should not port changes which are already at official repo

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/charts#68]
When someone from community sends PR to our official helm chart, we need to port it to this repo:
https://github.com/hazelcast/charts/pull/60
https://github.com/helm/charts/pull/17193

Even if developer copies changes from official repo without any modification, `git` can find unimportant diffs(whitespace etc). In such cases, the `create-pr-at-official-helm-repo` script should not create nonsense PR at official repo. 

To prevent it, developer can put special string like `[not-sync]` into commit message so  `create-pr-at-official-helm-repo` script can parse it. WDYT? @leszko @eminn

**Comment by leszko** [comment]
Good idea, we should implement it 👍
