### ISSUE TITLE
Convert EE READMEs to asciidoc(.adoc)

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/charts#72]
We are using two different type of README at OS(.adoc) and EE(.md) charts. Using same file type would be good for development process.

https://github.com/hazelcast/charts/pull/71

**Comment by sjha2048** [comment]
hello @mesutcelik , I would like to take up this issue.

**Comment by mesutcelik** [comment]
@sjha2048 Thanks a lot! Documentation is always a great start for any contributions!

**Comment by sjha2048** [comment]
Thank you @mesutcelik , I have opened a PR regarding same and looking forward to contributing to Hazelcast :)
