### ISSUE TITLE
Prometheus Scraping on 5701 in addition to 8080

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/charts#74]
When you install hazelcast helm chart with `metrics.enabled=true`, Prometheus tries to scrape 2 ports on hazelcast member port. 5701 should not be scraped as hazelcast publishes metrics on 8080.

![image](https://user-images.githubusercontent.com/823273/67637906-88d5e900-f8b5-11e9-98f0-0b5ec26abb53.png)

**Comment by lucas-svieira** [comment]
I'd like to take a shot at it!

**Comment by hasancelik** [comment]
Sounds perfect @lucas-svieira, I assigned you to this GH issue 👍  Looking forward to your contribution!

**Comment by Holmistr** [comment]
@lucas-svieira We're going to circle back internally on how to provide the initial guidance. We'll get back to you soon.

**Comment by lucas-svieira** [comment]
@Holmistr ok, great! I already set up a Minikube instance and installed hazelcast using Helm. For some reason, the mancenter keeps crashing, but I'll check why later.

I've already took a quick look at the configuration files but found nothing out of ordinary, and the only port I saw configured for Prometheus scraping was 8080. Let's see where do we go from here.

**Comment by mesutcelik** [comment]
Hi @lucas-svieira , Do you see the same error on Prometheus Dashboard that I shared on the screenshot? Prometheus is trying to scrape port 5701 where it shouldn't so it fails. 

I assume there is a problem with some labels or annotations.

**Comment by lucas-svieira** [comment]
@mesutcelik well, I'm not actually able to identify where is that screen you posted, if you could point me the direction. I was able to bring everything up and I can hit the /metrics endpoint, I'm just not able to find this screen.

**Comment by lucas-svieira** [comment]
@mesutcelik I just got everything running and, yes, it's trying to scrape port 5701 on each Hazelcast instance. I'll take a look around to see if I figure something out.
