### ISSUE TITLE
OpenSSL Read-only file system problem

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/charts#75]
**How to reproduce**

Create a keystore with key and certificates
```
kubectl create secret generic keystore --from-file=key.pem --from-file=chain.pem --from-file=cert.pem
```
Install hazelcast-enterprise with the following command
```
helm install --name hazelcast-openssl \
  --set hazelcast.licenseKey=<license-key>  \
  --set hazelcast.ssl=true \
  --set secretsMountName=keystore \
  --set hazelcast.yaml.hazelcast.network.ssl.factory-class-name=com.hazelcast.nio.ssl.OpenSSLEngineFactory \
  --set hazelcast.yaml.hazelcast.network.ssl.properties.keyFile=/data/secrets/key.pem \
  --set hazelcast.yaml.hazelcast.network.ssl.properties.trustCertCollectionFile=/data/secrets/cert.pem \
  --set hazelcast.yaml.hazelcast.network.ssl.properties.keyCertChainFile=/data/secrets/chain.pem \
  hazelcast/hazelcast-enterprise
```
The exception on the hazelcast member log says readonly filesystem.
```
	Caused by: java.io.IOException: Read-only file system
		at java.io.UnixFileSystem.createFileExclusively(Native Method)
		at java.io.File.createTempFile(File.java:2024)
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:183)

```

**Workaround**
Making [this](https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/templates/statefulset.yaml#L133) explicitly `readOnlyRootFilesystem: false` fixes the problem.

**Comment by mesutcelik** [comment]
@kwart What do you think about that issue? Do you think OpenSSL requires write permission on filesystem?

**Comment by kwart** [comment]
Native JNI bindings, which are located under the `META-INF/native/` of the `netty` JARs, have to be unpacked before loading.

So yes, to use OpenSSL/BoringSSL you need a writeable FS. You could also install the natives manually first to a location listed in `java.library.path`, then you should be OK with the read-only FS, I guess.

If you have a writable directory somewhere on your system, you can also use the `io.netty.native.workdir` System property to control where the natives will be unpacked.
