### ISSUE TITLE
Use VolumeClaimTemplates instead of PersistentVolumeClaim for Hot Restart

### ISSUE THREAD

**Issue by leszko** [hazelcast/charts#95]
Using `VolumeClaimTemplates` (as described [here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components)) would make each Hazelcast member receive a separate `PersistentVolume` for the Hot Restart directory. That would enable using `ReadWriteOnce` PersistentVolumes. Currently we can use only use `ReadWriteMany`.

**Comment by cristina-sirbu** [comment]
Hello! Can I take this task?

**Comment by mesutcelik** [comment]
Thanks @cristina-sirbu! It is already yours...

**Comment by leszko** [comment]
Thansk @cristina-sirbu , thanks for taking this issue. If you have any questions or clarifications, let us know!

**Comment by mesutcelik** [comment]
Hi @cristina-sirbu ,
Do you need any help on this? I see the issue is not updated lately so if you are stuck at some point, just let us know.

**Comment by cristina-sirbu** [comment]
Hello @mesutcelik!
Sorry for my absence. I think I've finished it. I created a PR with a version of what I've done. When you will have time can you please take a look and let me know if I've accomplished what was expected for this issue?

**Comment by leszko** [comment]
@cristina-sirbu Thanks a lot for the PR, we'll review it soon :)

**Comment by leszko** [comment]
Fixed by #119 thanks to @cristina-sirbu
